services:
  - type: web
    name: babembe-community-site
    env: static
    buildCommand: npm install --force && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
